using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.2.1.0")]
[assembly: AssemblyTitleAttribute("StyleCopCmd")]
[assembly: AssemblyProductAttribute("StyleCopCmd")]
[assembly: AssemblyCompanyAttribute("The McCombs School of Business at the University of Texas at Austin")]
[assembly: AssemblyDescriptionAttribute("StyleCopCmd provides a command-line interface and NAnt task to StyleCop")]
[assembly: AssemblyCopyrightAttribute("Copyright © Schley Andrew Kutz 2008")]

